#!/usr/bin/perl -w
# MILO quick test script: Discovery Studio / CHARMm / Minimization (ethanol)
# Generated by the MILO MCP.  Bundle ID: {{BUNDLE_ID}}
#
# HOW TO RUN (on the VM):
#   1. Check MILO_DROP_DIR below points at the folder MILO reads (shared with the host).
#   2. Discovery Studio must be connected to its Pipeline Pilot server (the protocol runs there).
#   3. Save this as a .pl file, open it in Discovery Studio's Script Window, and click Run
#      (or drag the file into Discovery Studio, or: "<DS Install Folder>\bin\perl.bat" this_script.pl).
#   4. When it finishes, the bundle appears in MILO_DROP_DIR/{{BUNDLE_ID}}/ (and a copy stays in the work folder).
use strict;
use MdmDiscoveryScript;
use ProtocolDiscoveryScript;
use ForceFieldDiscoveryScript;

my $MILO_BUNDLE_ID = '{{BUNDLE_ID}}';
my $MILO_DROP_DIR = '{{DROP_DIR}}';
my $MILO_CAMPAIGN = {{CAMPAIGN}};  # the campaign this run belongs to, or undef

{{BUNDLE_WRITER}}

# Every parameter this run changes. The protocol's COMPLETE parameter set (including untouched defaults)
# is dumped into INPUT/files/settings/ by apply_parameters.
my @MINIMIZATION_PARAMETERS = (
    ["Minimization Algorithm", "Smart Minimizer", undef],
    ["Minimization Max Steps", 500, undef],
    ["Minimization RMS Gradient", 0.1, "kcal/(mol*A)"],
    ["Implicit Solvent Model", "None", undef],
);
my $SMILES = "CCO";
my $MAX_DOWNLOAD_MB = 256;

my $work_dir = DiscoveryScript::GetTemporaryFolder();
my $bundle = MiloBundle->new(
    bundle_id => $MILO_BUNDLE_ID, product => "Discovery Studio", module => "CHARMm", task => "Minimization",
    drop_dir => $MILO_DROP_DIR, work_dir => $work_dir, title => "Ethanol minimization (test)",
    campaign => $MILO_CAMPAIGN,
);
my $status = "failed";
eval {
    # ---------------- INPUT ----------------
    $bundle->input("perl_version", sprintf("%vd", $^V));
    $bundle->input("host", $ENV{COMPUTERNAME} || $ENV{HOSTNAME});
    $bundle->input("accelrys_root", $ENV{ACCELRYS_ROOT} || $ENV{AccelrysRoot});
    $bundle->input_file($0, "script.pl") if -f $0;

    # Input structure: ethanol from SMILES, hydrogens added, cleaned, typed with CHARMm.
    my $document = Mdm::Document::Create();
    $document->InsertFromSmiles($SMILES);
    $document->AddHydrogenAtoms();
    $document->Clean();
    my $forcefield = Ffdm::Document::Create(Ffdm::charmmForceField);
    my $typing = $forcefield->ApplyForceField($document, True, True, True, Ffdm::useMomanyRonePartialCharges);
    die "CHARMm typing failed (status $typing)\n" unless $typing == Ffdm::applyForceFieldCompleted;
    $bundle->input("structure_smiles", $SMILES);
    $bundle->input("structure_atom_count", $document->Atoms->Count);
    $bundle->input("forcefield", "CHARMm");
    $bundle->input("partial_charge_method", "Momany-Rone");
    $bundle->record_molecules("input_molecule", $document, "INPUT");
    my $input_structure = $bundle->input_path("input_structure.dsv");
    $document->Save($input_structure, "dsv");
    $forcefield->Save($bundle->input_path("forcefield.ffml"));

    # Protocol: connect, create, apply every parameter, dump the full parameter set.
    my $session = Protocol::Document::DefaultSession()
        or die "No Pipeline Pilot server connection. Connect Discovery Studio to its server and run again.\n";
    $bundle->input("server", $bundle->safe($session, "Server"));
    $bundle->input("server_user", $bundle->safe($session, "User"));
    $bundle->input("max_download_mb", $MAX_DOWNLOAD_MB, "MB");
    my $protocol = Protocol::Document::Create("Minimization", $session);
    $bundle->input("protocol_name", "Minimization");
    $bundle->input("protocol_version", $bundle->safe($protocol, "Version"));
    $bundle->input("protocol_guid", $bundle->safe($protocol, "Guid"));
    $bundle->apply_parameters($protocol, undef, [
        ["Input Typed Molecule", $input_structure, undef],
        @MINIMIZATION_PARAMETERS,
    ]);

    # ---------------- RUN ----------------
    my $task = $bundle->timed(sub {
        my $task = $session->Launch($protocol, $MAX_DOWNLOAD_MB, True, False);
        $task->WaitForCompletion();
        return $task;
    });

    # ---------------- OUTPUT ----------------
    my $files = $bundle->record_task(undef, $task);
    my $state = $bundle->safe($task, "State");
    my $ok = defined $state && $state eq Protocol::taskComplete && $bundle->safe($task, "IsProtocolSuccessful");
    for my $rel (grep { m{^Output/.*\.(dsv|msv|sd|mol2|pdb)$}i } @$files) {
        my $result = DiscoveryScript::Open({Path => $task->RunPath . "/" . $rel, LoadAllObjects => True});
        (my $label = $rel) =~ s{^Output/|\.\w+$}{}g;
        $bundle->record_molecules("result." . $label, $result);
    }
    $status = $ok ? "succeeded" : "failed";
    1;
} or do {
    $bundle->record_error($@);
    $status = "failed";
};
$bundle->finish($status);
