#!python
# MILO quick test script: Materials Studio / Forcite / Geometry Optimization (water)
# Generated by the MILO MCP.  Bundle ID: {{BUNDLE_ID}}
#
# HOW TO RUN (on the VM):
#   1. Check MILO_DROP_DIR below points at the folder MILO reads (shared with the host).
#   2. In Materials Studio: File > New > Python script (or import this .py), paste, and Run on the Server.
#   3. When it finishes, the bundle appears in MILO_DROP_DIR/{{BUNDLE_ID}}/ (and a copy stays in the job folder).
from PyMaterialsScript import *

MILO_BUNDLE_ID = "{{BUNDLE_ID}}"
MILO_DROP_DIR = r"{{DROP_DIR}}"

{{BUNDLE_WRITER}}

import platform

# Every setting this run changes, in the order applied (Quality first: it resets quality-dependent settings).
# The COMPLETE settings in effect (including untouched defaults) are dumped with SaveSettings into INPUT/files.
FORCITE_SETTINGS = [
    ("Quality", "Coarse", None),
    ("CurrentForcefield", "Universal", None),
    ("ChargeAssignment", "Forcefield assigned", None),
    ("OptimizationAlgorithm", "Smart", None),
    ("MaxIterations", 500, None),
    ("UseMaxEnergy", "Yes", None),
    ("MaxEnergy", 0.001, "kcal/mol"),
    ("UseMaxForce", "Yes", None),
    ("MaxForce", 0.5, "kcal/mol/A"),
    ("UseMaxDisplacement", "Yes", None),
    ("MaxDisplacement", 0.015, "A"),
    ("MaxShiftAllowed", 2.0, "A"),
    ("OptimizeCell", "No", None),
    ("WriteLevel", "Summary", None),
]


bundle = MiloBundle(MILO_BUNDLE_ID, "Materials Studio", "Forcite", "Geometry Optimization", MILO_DROP_DIR,
                    title="Water geometry optimization (test)")
status = "failed"
try:
    # ---------------- INPUT ----------------
    bundle.input("python_version", platform.python_version())
    bundle.input("host", _milo_os.environ.get("COMPUTERNAME") or platform.node())
    bundle.input("cpu_count", _milo_os.cpu_count())
    for candidate in (globals().get("__file__"), _milo_sys.argv[0] if _milo_sys.argv else None):
        if candidate and _milo_os.path.isfile(candidate):
            bundle.input_file(candidate, "script.py")
            break

    # Input structure: one water molecule built in the script.
    doc = Documents.New("milo_water.xsd")
    O = doc.CreateAtom("O", Point())
    H1 = doc.CreateAtom("H", Point(X=0.96))
    H2 = doc.CreateAtom("H", Point(X=-0.24, Y=0.93))
    doc.CreateBond(O, H1, "Single")
    doc.CreateBond(O, H2, "Single")
    bundle.input("structure_name", "water")
    bundle.input("structure_atom_count", doc.Atoms.Count)
    bundle.input("structure_elements", [atom.ElementSymbol for atom in doc.Atoms])
    doc.Export(bundle.input_path("input_structure.xsd"))

    # Settings: apply, record each one, then dump the full settings actually in effect.
    bundle.apply_settings(Modules.Forcite, None, FORCITE_SETTINGS, dump_name="milo_forcite_settings")

    # ---------------- RUN ----------------
    before_run = bundle.snapshot()
    with bundle.timed():
        results = Modules.Forcite.GeometryOptimization.Run(doc)

    # ---------------- OUTPUT ----------------
    bundle.output("Converged", results.Converged)
    try:
        bundle.output("TotalEnthalpy", results.TotalEnthalpy, "kcal/mol")
    except Exception:
        pass  # only defined for 3D-periodic structures
    bundle.record_energies(None, doc)
    bundle.record_results(None, results, report_name="forcite")
    doc.Export(bundle.output_path("optimized_structure.xsd"))
    Documents.SaveAll()
    bundle.output("job_files", bundle.capture_new_files(before_run, "OUTPUT", "job"))
    status = "succeeded" if results.Converged else "not_converged"
except Exception as exc:
    bundle.record_error(exc)
    status = "failed"
finally:
    bundle.finish(status)
