#!python
# MILO script: Materials Studio / Amorphous Cell + Forcite — PLA/PCL blend amorphous cell
# Generated by the MILO MCP.  Bundle ID: {{BUNDLE_ID}}
#
# Workflow (all inside this one script, no input files needed):
#   1. Build PLA and PCL repeat units, grow chains with the Polymer Builder.
#   2. Pack them into a 3D-periodic amorphous cell at the requested mass fraction (Amorphous Cell Construction).
#   3. Forcite geometry optimization of the cell.
#   4. Forcite NPT dynamics sized to fill the time budget (a short probe run measures speed first).
# Every setting applied is recorded, and each module's FULL settings are dumped with SaveSettings into INPUT.
# Every value, report, structure, trajectory and job file produced goes to OUTPUT.
#
# HOW TO RUN (on the VM): new Python script document in Materials Studio -> paste -> Run on the Server.
# The bundle is written to MILO_DROP_DIR/{{BUNDLE_ID}}/ (a copy also stays in the job folder).
from PyMaterialsScript import *

MILO_BUNDLE_ID = "{{BUNDLE_ID}}"
MILO_DROP_DIR = r"{{DROP_DIR}}"
MILO_CAMPAIGN = {{CAMPAIGN}}  # the campaign this run belongs to, or None
MILO_PARAMS = {{PARAMS}}

{{BUNDLE_WRITER}}

import platform

P = MILO_PARAMS
SCRIPT_T0 = _milo_time.perf_counter()
TAG = "PLA%02d_PCL%02d" % (round(100 * P["pla_mass_fraction"]), round(100 * (1 - P["pla_mass_fraction"])))
bundle = MiloBundle(MILO_BUNDLE_ID, "Materials Studio", "Amorphous Cell + Forcite",
                    "PLA/PCL amorphous cell: construction, geometry optimization, NPT dynamics", MILO_DROP_DIR,
                    title="%s amorphous cell" % TAG.replace("_", "/"), campaign=MILO_CAMPAIGN)


def elapsed():
    return _milo_time.perf_counter() - SCRIPT_T0


def mass_of(doc):
    return sum(atom.Mass for atom in doc.Atoms)


def build_repeat_unit(name, atoms, bonds, head, tail, chiral=None):
    """atoms: [(label, element, x, y, z)], bonds: [(label1, label2, type)]; head/tail are terminal H labels."""
    doc = Documents.New(name + "_repeat_unit.xsd")
    made = {}
    for label, element, x, y, z in atoms:
        made[label] = doc.CreateAtom(element, Point(X=x, Y=y, Z=z))
    for a, b, kind in bonds:
        doc.CreateBond(made[a], made[b], kind)
    doc.Clean()
    if chiral:
        unit = doc.CreateRepeatUnit(made[head], made[tail], made[chiral])
    else:
        unit = doc.CreateRepeatUnit(made[head], made[tail])
    return doc, unit


# PLA repeat unit  H(head)-CH(CH3)-C(=O)-O-H(tail); the alpha carbon is the chiral center (isotactic -> PLLA-like)
PLA_ATOMS = [
    ("Hh", "H", -1.0, 0.0, 0.0), ("Ca", "C", 0.0, 0.0, 0.0), ("Ha", "H", 0.0, 1.0, 0.3),
    ("Cm", "C", 0.0, -0.8, 1.3), ("Hm1", "H", 0.9, -0.6, 1.9), ("Hm2", "H", -0.9, -0.6, 1.9), ("Hm3", "H", 0.0, -1.8, 1.0),
    ("Cc", "C", 1.4, -0.4, -0.5), ("Oc", "O", 1.7, -1.5, -0.9), ("Oe", "O", 2.4, 0.5, -0.4), ("Ht", "H", 3.2, 0.2, -0.8),
]
PLA_BONDS = [
    ("Hh", "Ca", "Single"), ("Ca", "Ha", "Single"), ("Ca", "Cm", "Single"), ("Cm", "Hm1", "Single"),
    ("Cm", "Hm2", "Single"), ("Cm", "Hm3", "Single"), ("Ca", "Cc", "Single"), ("Cc", "Oc", "Double"),
    ("Cc", "Oe", "Single"), ("Oe", "Ht", "Single"),
]
# PCL repeat unit  H(head)-(CH2)5-C(=O)-O-H(tail)
PCL_ATOMS = [("Hh", "H", -1.0, 0.0, 0.0)]
PCL_BONDS = []
previous = "Hh"
for i in range(5):
    c = "C%d" % i
    PCL_ATOMS += [(c, "C", 1.3 * i, 0.4 * (i % 2), 0.0), (c + "a", "H", 1.3 * i, 0.4 * (i % 2) + 0.6, 0.9),
                  (c + "b", "H", 1.3 * i, 0.4 * (i % 2) + 0.6, -0.9)]
    PCL_BONDS += [(previous, c, "Single"), (c, c + "a", "Single"), (c, c + "b", "Single")]
    previous = c
PCL_ATOMS += [("Cc", "C", 6.5, 0.0, 0.0), ("Oc", "O", 6.8, -1.2, 0.0), ("Oe", "O", 7.5, 0.9, 0.0), ("Ht", "H", 8.4, 0.6, 0.0)]
PCL_BONDS += [("C4", "Cc", "Single"), ("Cc", "Oc", "Double"), ("Cc", "Oe", "Single"), ("Oe", "Ht", "Single")]


def build_chain(name, unit, unit_doc, repeats):
    """Homopolymer.Build takes a RepeatUnit; the docs' own example passes the repeat-unit document, so try both."""
    chain = Documents.New(name)
    try:
        Tools.PolymerBuilder.Homopolymer.Build(chain, unit, repeats)
    except Exception:
        Tools.PolymerBuilder.Homopolymer.Build(chain, unit_doc, repeats)
    return chain


def choose_counts(mass_pla, mass_pcl, fraction_pla, total):
    """Integer chain counts whose MASS fraction is closest to the target."""
    best = None
    for n_pla in range(1, total):
        n_pcl = total - n_pla
        achieved = n_pla * mass_pla / (n_pla * mass_pla + n_pcl * mass_pcl)
        if best is None or abs(achieved - fraction_pla) < abs(best[2] - fraction_pla):
            best = (n_pla, n_pcl, achieved)
    return best


status = "failed"
try:
    with bundle.timed():
        # ================= INPUT: environment + requested parameters =================
        bundle.input("python_version", platform.python_version())
        bundle.input("host", _milo_os.environ.get("COMPUTERNAME") or platform.node())
        bundle.input("cpu_count", _milo_os.cpu_count())
        for candidate in (globals().get("__file__"), _milo_sys.argv[0] if _milo_sys.argv else None):
            if candidate and _milo_os.path.isfile(candidate):
                bundle.input_file(candidate, "script.py")
                break
        for key, value in P.items():
            bundle.input("requested." + key, value)

        # ================= INPUT: chains =================
        bundle.apply_settings(Tools.PolymerBuilder, "PolymerBuilder", [
            ("Tacticity", "Isotactic", None),
            ("Orientation", "Head-to-Tail", None),
            ("Torsion", 180.0, "deg"),
        ])
        pla_ru_doc, pla_ru = build_repeat_unit("PLA", PLA_ATOMS, PLA_BONDS, "Hh", "Ht", chiral="Ca")
        pcl_ru_doc, pcl_ru = build_repeat_unit("PCL", PCL_ATOMS, PCL_BONDS, "Hh", "Ht")
        pla_chain = build_chain("PLA_%dmer.xsd" % P["repeat_units"], pla_ru, pla_ru_doc, P["repeat_units"])
        pcl_chain = build_chain("PCL_%dmer.xsd" % P["repeat_units"], pcl_ru, pcl_ru_doc, P["repeat_units"])

        mass_pla, mass_pcl = mass_of(pla_chain), mass_of(pcl_chain)
        n_pla, n_pcl, achieved = choose_counts(mass_pla, mass_pcl, P["pla_mass_fraction"], P["total_chains"])
        for label, doc, mass, count in (("PLA", pla_chain, mass_pla, n_pla), ("PCL", pcl_chain, mass_pcl, n_pcl)):
            bundle.input(label + ".repeat_units", P["repeat_units"])
            bundle.input(label + ".chain_atoms", doc.Atoms.Count)
            bundle.input(label + ".chain_mass", mass, "amu")
            bundle.input(label + ".chain_count", count)
            bundle.input(label + ".chain_formula", bundle.safe(doc, "ChemicalFormula"))
            doc.Export(bundle.input_path(label + "_chain.xsd"))
        pla_ru_doc.Export(bundle.input_path("PLA_repeat_unit.xsd"))
        pcl_ru_doc.Export(bundle.input_path("PCL_repeat_unit.xsd"))
        bundle.input("PLA_mass_fraction_actual", achieved)
        bundle.input("total_atoms", n_pla * pla_chain.Atoms.Count + n_pcl * pcl_chain.Atoms.Count)
        Documents.SaveAll()  # inputs exist on disk before the run, so the job sweep below only catches outputs

        # ================= RUN 1: Amorphous Cell construction (forcefield fallback) =================
        before_run = bundle.snapshot()
        construction = Modules.AmorphousCell.Construction
        construction.AddComponent(pla_chain)
        construction.Loading[pla_chain] = n_pla
        construction.AddComponent(pcl_chain)
        construction.Loading[pcl_chain] = n_pcl
        forcefield = None
        ac_results = None
        for candidate_ff in (P["forcefield"], "Universal"):
            try:
                bundle.apply_settings(Modules.AmorphousCell, "AmorphousCell", [
                    ("Quality", "Coarse", None),
                    ("CurrentForcefield", candidate_ff, None),
                    ("Configurations", 1, None),
                    ("TargetDensity", P["construction_density"], "g/cm^3"),
                    ("Temperature", P["temperature_k"], "K"),
                    ("OptimizeGeometry", "No", None),
                    ("LoadingMoves", 1000, None),
                ])
                t0 = _milo_time.perf_counter()
                ac_results = construction.Run()
                bundle.output("AmorphousCell.stage_time", _milo_time.perf_counter() - t0, "s")
                forcefield = candidate_ff
                break
            except Exception as exc:
                bundle.output("AmorphousCell.failed_with_" + candidate_ff, "%s: %s" % (type(exc).__name__, exc))
                if candidate_ff == "Universal":
                    raise
        bundle.input("forcefield_used", forcefield)
        bundle.record_results("AmorphousCell", ac_results)
        cell = Documents.New("%s_cell.xsd" % TAG)
        cell.CopyFrom(ac_results.Trajectory)
        bundle.record_cell("AmorphousCell", cell)
        cell.Export(bundle.output_path("amorphous_cell_packed.xsd"))

        # ================= RUN 2: Forcite geometry optimization =================
        bundle.apply_settings(Modules.Forcite, "GeometryOptimization", [
            ("Quality", "Coarse", None),
            ("CurrentForcefield", forcefield, None),
            ("OptimizationAlgorithm", "Smart", None),
            ("MaxIterations", P["geomopt_max_iterations"], None),
            ("OptimizeCell", "No", None),
            ("WriteLevel", "Summary", None),
        ])
        t0 = _milo_time.perf_counter()
        opt_results = Modules.Forcite.GeometryOptimization.Run(cell)
        bundle.output("GeometryOptimization.stage_time", _milo_time.perf_counter() - t0, "s")
        bundle.record_results("GeometryOptimization", opt_results, [("Converged", None)])
        bundle.record_energies("GeometryOptimization", cell)
        bundle.record_cell("GeometryOptimization", cell)
        cell.Export(bundle.output_path("amorphous_cell_optimized.xsd"))

        # ================= RUN 3: NPT dynamics, sized to the time budget =================
        dyn_settings = [
            ("Quality", "Coarse", None),
            ("CurrentForcefield", forcefield, None),
            ("Ensemble3D", "NPT", None),
            ("Temperature", P["temperature_k"], "K"),
            ("Pressure", P["pressure_gpa"], "GPa"),
            ("Thermostat", "Nose", None),
            ("Barostat", "Berendsen", None),
            ("TimeStep", 1.0, "fs"),
            ("InitialVelocities", "Random", None),
            ("RandomSeed", P["random_seed"], None),
            ("WriteLevel", "Summary", None),
        ]
        probe_steps = 500
        bundle.apply_settings(Modules.Forcite, "NPTProbe", dyn_settings + [
            ("NumberOfSteps", probe_steps, None), ("TrajectoryFrequency", probe_steps, None)])
        probe = Documents.New("%s_probe.xsd" % TAG)
        probe.CopyFrom(cell)
        t0 = _milo_time.perf_counter()
        Modules.Forcite.Dynamics.Run(probe)
        seconds_per_step = (_milo_time.perf_counter() - t0) / probe_steps
        bundle.output("NPTProbe.seconds_per_step", seconds_per_step, "s")

        budget = 60.0 * P["time_budget_min"]
        remaining = budget - elapsed() - 20.0  # leave time for writing the bundle
        frames = P["trajectory_frames"]
        steps = int(max(1000, min(P["max_npt_steps"], remaining / max(seconds_per_step, 1e-6))))
        freq = max(1, steps // frames)
        steps = freq * frames
        bundle.input("NPT.time_budget", budget, "s")
        bundle.input("NPT.remaining_budget_at_start", remaining, "s")
        bundle.apply_settings(Modules.Forcite, "NPT", dyn_settings + [
            ("NumberOfSteps", steps, None), ("TrajectoryFrequency", freq, None)])
        npt = Documents.New("%s_npt.xsd" % TAG)
        npt.CopyFrom(cell)
        t0 = _milo_time.perf_counter()
        npt_results = Modules.Forcite.Dynamics.Run(npt)
        bundle.output("NPT.stage_time", _milo_time.perf_counter() - t0, "s")
        bundle.output("NPT.simulated_time", steps * 1.0 / 1000.0, "ps")
        bundle.record_results("NPT", npt_results, [
            ("Density", "g/cm^3"), ("CellVolume", "A^3"), ("Temperature", "K"), ("Pressure", "GPa"),
            ("PotentialEnergy", "kcal/mol"), ("KineticEnergy", "kcal/mol"), ("TotalEnergy", "kcal/mol"),
            ("TotalEnthalpy", "kcal/mol"), ("StressXX", "GPa"), ("StressYY", "GPa"), ("StressZZ", "GPa"),
            ("StressYZ", "GPa"), ("StressXZ", "GPa"), ("StressXY", "GPa"),
        ])
        bundle.record_energies("NPT.final_frame", npt)
        bundle.record_cell("NPT.final_frame", npt)
        npt.Export(bundle.output_path("amorphous_cell_final.xsd"))
        trajectory = bundle.safe(npt_results, "Trajectory")
        if trajectory is not None:
            bundle.output("NPT.trajectory_frames", bundle.safe(bundle.safe(trajectory, "Trajectory"), "NumFrames"))

        Documents.SaveAll()
        bundle.output("job_files", bundle.capture_new_files(before_run, "OUTPUT", "job"))
        status = "succeeded"
except Exception as exc:
    bundle.record_error(exc)
    status = "failed"
finally:
    bundle.output("script_total_time", elapsed(), "s")
    bundle.finish(status)
